runtime: python312
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

automatic_scaling:
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.65

env_variables:
  FRONTEND_BASE_URL: "https://coffee.coffeequant.com"
  GOOGLE_CLIENT_ID: "58596950813-89s7vbdb1lnhom1t93mc979lgp5143eo.apps.googleusercontent.com"
  STRIPE_SECRET_KEY: "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"
  STRIPE_PRICE_ID_YEARLY: "price_1SWJKRRzxxClYou2DPfdr0lu"
  STRIPE_WEBHOOK_SECRET: "whsec_bLJUL3vJ5WxpS9YkiH5e9TvzkdrT6P0D"


handlers:
  - url: /statics
    static_dir: statics
    secure: always

  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico
    secure: always

  - url: /.*
    script: auto
    secure: always
