runtime: python312

handlers:
  # Serve all static files (HTML, CSS, JS, images, JSON, etc.)
  - url: /(.*\.(html|css|js|json|png|jpg|jpeg|gif|webp|svg|ico|txt|pdf|woff2?))$
    static_files: \1
    upload: (.*\.(html|css|js|json|png|jpg|jpeg|gif|webp|svg|ico|txt|pdf|woff2?))$
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      Cache-Control: "public, max-age=3600"

  # Serve everything else (like /labs, /notes, /tools) as index.html
  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      Cache-Control: "no-cache"
